- name: "HTH | Identities | Dirs | Manage path"
  ansible.builtin.file:
    path: "{{ path_prefix }}{{ path }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ dir.mode | default('0755') }}"
    state: "{{ 'absent' if (dir.remove | default(false)) else 'directory' }}"
    force: "{{ dir.force | default(false) }}"
    recurse: "{{ true if (dir.recurse | default(false)) else false }}"
    access_time: preserve
    modification_time: preserve
  loop: "{{ dir.path if (dir.path is iterable and dir.path is not string) else [dir.path] }}"
  loop_control:
    loop_var: "path"
