- name: "identities | files | copy over file"
  ansible.builtin.copy:
    src: "{{ file.source }}"
    dest: "{{ path_prefix }}{{ file.path }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ file.mode | default('0644') }}"
    force: "{{ file.force | default(false) }}"
    backup: "{{ file.backup | default(false) }}"
  when:
    - file.remove is undefined or not file.remove
    - file.source is defined

- name: "identities | files | stat file"
  ansible.builtin.stat:
    path: "{{ path_prefix }}{{ file.path }}"
  register: file_stats
  when:
    - file.source is undefined

- name: "identities | files | modify file"
  ansible.builtin.file:
    path: "{{ path_prefix }}{{ file.path }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ file.mode | default('0644') }}"
    state : "{{ 'absent' if (file.remove is defined and file.remove) else 'file' if (file_stats.stat.exists) else 'touch' }}"
  when:
    - file.source is undefined
