# -----------------------------------------------------------------------------
# This file contains task related to managing groups.
#
# It expects to be iterated over with a input variable named 'group'
# -----------------------------------------------------------------------------

- name: users | groups | manage group
  ansible.builtin.group:
    name: "{{ group.name }}"
    gid: "{{ group.id | default(omit) }}"
    state: "{{ group.state | default('present')}}"
  when:
    - group is defined
