- name: identities | assertion | run assertions
  ansible.utils.validate:
    data: "{{ identities }}"
    criteria: "{{ lookup('file', 'assertions/criteria/identities-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost
  when:
    - identities is defined

- name: identities | groups | modify groups
  ansible.builtin.group:
    name: "{{ group.name }}"
    gid: "{{ group.id | default(omit) }}"
    state: "{{ group.state | default('present')}}"
  loop: "{{ identities.groups }}"
  loop_control:
    loop_var: group
  when:
    - identities is defined
    - identities.groups is defined

- name: identities | users | modify users
  ansible.builtin.include_tasks: user.yml
  loop: "{{ identities.users }}"
  loop_control:
    loop_var: user
  when:
    - identities is defined
    - identities.users is defined

- name: identities | root
  ansible.builtin.include_tasks: root.yml
  when:
    - identities is defined
    - identities.root is defined
