- name: "HTH | Identities | Root | Disable root login"
  become: true
  ansible.builtin.user:
    shell: /usr/sbin/nologin
    name: root
  when:
    - users.root is defined
    - users.root.login == false
