- name: "HTH | Identities | Files | Write value to file"
  ansible.builtin.copy:
    content: "{{ file.source }}"
    dest: "{{ file_path }}"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    mode: "{{ file_mode }}"
    force: "{{ file_force }}"
    backup: "{{ file_backup }}"
  when:
    - file.type == 'value'

- name: "HTH | Identities | Files | Write variable to file"
  ansible.builtin.copy:
    content: "{{ lookup('vars', file.source) | trim }}"
    dest: "{{ file_path }}"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    mode: "{{ file_mode }}"
    force: "{{ file_force }}"
    backup: "{{ file_backup }}"
  when:
    - file.type == 'variable'
