---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  roles:
  - role: hth.identities
    vars:
      variable_file_content: "This is the variable content"
      identities:
        users:
          - id: 1234
            name: bob
            home:
              state: present
              files:
                - source: "copy-file"
                  path: "copy-file"
                  type: copy
                - source: "copy-file"
                  path: "backup-file"
                  backup: true
                  force: true
                  type: copy
                - source: "copy-file"
                  path: "overwrite-file"
                  type: copy
                - path: "modify-mode-file"
                  mode: "0600"
                  type: copy
                - path: "create-file"
                  type: copy
                - path: "remove-file"
                  remove: true
                  type: copy
                - source: "template-file"
                  path: "templated-file.yml"
                  type: template
                  vars:
                    variable: "some value"
                - path: "remove-template-file"
                  type: template
                  remove: true
                - path: "value-file"
                  type: value
                  source: "This is the value content"
                - path: "variable-file"
                  type: variable
                  source: "variable_file_content"
